export const ID_COLLECTION_DELETE = 'ID_COLLECTION_DELETE';
export const ID_COLLECTION_EDIT = 'ID_COLLECTION_EDIT';
export const ID_CATEGORY_CREATE = 'ID_CATEGORY_CREATE';
export const ID_CATEGORY_EDIT = 'ID_CATEGORY_EDIT';
